### ISSUE TITLE
Exclude file redirects from user/category listing

### ISSUE THREAD

**Issue by simon04** [simon04/locator-tool#12]
Example https://commons.wikimedia.org/w/index.php?title=File:Altes_Schloss_Valley_-_Bundwerkstadel_02.JPG&redirect=no

**Comment by Nudin** [comment]
I forgot about this bug and just rediscovered it. ;) Here the screenshot I created before finding this ticket…
![locatortool-bug](https://user-images.githubusercontent.com/509205/41228199-c9438b7a-6d77-11e8-89ea-fefeed612ea3.png)
