### ISSUE TITLE
Make "select files to geolocate" more prominent

### ISSUE THREAD

**Issue by jdittrich** [simon04/locator-tool#15]
Currently the button looks like 
![image](https://cloud.githubusercontent.com/assets/3416487/26284042/c5f05c20-3e32-11e7-8a03-a350ecb63c4b.png)
It might need to be the most prominent button on the page.

**Comment by simon04** [comment]
Since f7ed2207c88370049f084ca72a472223ca25c641, the file selection is displayed immediately when opening https://tools.wmflabs.org/locator-tool/ and when clicking the locator-tool logo. Thus I wouldn't emphasis on it.
