### ISSUE TITLE
Use DeepCat for category listing

### ISSUE THREAD

**Issue by simon04** [simon04/locator-tool#22]
To improve the performance/availability for listing files in categories, PetScan could/should be replaced by DeepCat. Some documentation:

* https://wikitech.wikimedia.org/wiki/Nova_Resource:Catgraph/Documentation
* https://wikitech.wikimedia.org/wiki/Nova_Resource:Catgraph/Deepcat
* https://github.com/wmde/catgraph-jsonp

**Comment by simon04** [comment]
@jkroll20: I would like to use DeepCat for obtaining a recursive list of Commons files given a category name. With the query https://tools.wmflabs.org/catgraph-jsonp/commonswiki_ns14/traverse-successors%20Category:Innsbruck%203?callback=JSONP I manage to obtain the sub-category IDs, but I'd have to subsequently get a file listing of those categories. Is there a way to directly obtain a list of files (ns 6)?

**Comment by jkroll20** [comment]
We currently only carry the Category namespace in CatGraph. Tools then get the linked articles from MariaDB. Is that an option for you?

**Comment by simon04** [comment]
Di you know whether there's a MediaWiki API call or an existing tool on
Labs for that? That would avoid reenventing the wheel.

**Comment by jkroll20** [comment]
You could try the [Article List Generator Backend](http://tools.wmflabs.org/render/tlgbe/tlgwsgi.py) ([example query](http://tools.wmflabs.org/render/tlgbe/tlgwsgi.py?action=query&lang=de&query=Biologie&querydepth=2&flaws=ALL&chunked=true&format=json)). It can do category intersection, exclusion, and some [filtering](http://tools.wmflabs.org/render/tlgbe/tlgwsgi.py?action=listflaws).
