### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by wikimarcok** [simon04/locator-tool#24]
Hi, I'm a proud user of locator-tool, and I used it to geolocate a whole historical photoarchive (8.000+ photos, see [https://commons.wikimedia.org/wiki/Commons:BEIC]). I enjoyed all updates, but unfortunately I experiment that the procedure is seriously slowed down. When I submit a Commons category (even a small one), it takes several minutes (10-30+) to appear the geolocation page (and sometimes it doesn't appera at all). For example
https://tools.wmflabs.org/locator-tool/#/geolocate?category=Palazzo%20Viaro%20Zane%20(Venice)&categoryDepth=3
I'm experimenting this situation for a long time now, could you kindly fix it? Thanks!

**Comment by simon04** [comment]
The problem is that the category listing using PetScan is taking so long. In my tests, restricting the depth to 1 helped (but is not applicable to all categories/usecases). To increase the performance, #22 is a very promising way to go.

**Comment by simon04** [comment]
Category listing now uses two implementations different from PetScan. Automatically uses the faster one.
