### ISSUE TITLE
Getting file by user problem

### ISSUE THREAD

**Issue by frettie** [simon04/locator-tool#26]
Hello,
i have problem with selecting files by user name - i get user name (for me Frettie) or other names and i get 0 files and in Network tab i dont see any reactions of server. :/

Can you help me? Thx.

**Comment by simon04** [comment]
Thanks for the report. The long file names caused a problem with the former way of interacting with MediaWiki (causing too long URLs). I fixed that by switching to HTTP POST requests. You should be able to see your files now 😄

**Comment by frettie** [comment]
Thank you very much!
