### ISSUE TITLE
Allow me to "ignore" some pictures

### ISSUE THREAD

**Issue by nicolas-raoul** [simon04/locator-tool#39]
I like to keep some categories 100% geolocalized, coming back to them every few month to geolocalize the new ones that have arrived.

Problem: Some pictures (such as blasons, portraits of people associated with the category, etc) are not geolocalizable, and they stay in the way, making it difficult for me to quickly find whether there are new arrivals or not.

Possible solution: Add an "ignore" button that makes these images never show up to me again. Such as feature is already implemented in WDFIST (at two levels: just for me, or for everyone with a big common ignore list)

**Comment by valerio-bozzolan** [comment]
Hi! Great idea.

First question. Do you see a template here that could be useful to "mark a photo to be difficult to locate"?

If not, let's create it.

Then, we can just add an option to the tool to decide to skip that template/category.

**Comment by valerio-bozzolan** [comment]
Can this template represent that concept? Or is it too restrictive?

https://commons.wikimedia.org/wiki/Category:Location_not_applicable

**Comment by samwilson** [comment]
Maybe a `difficult=yes` parameter could be added to [{{location possible}}](https://commons.wikimedia.org/wiki/Template:Location_possible)?

**Comment by nicolas-raoul** [comment]
Great idea Valerio, being able to easily add `Location not applicable` or `Location withheld` sounds like a perfect solution!

I will close this issue as a duplicate of #4.
