### ISSUE TITLE
No CORS for showing images of category on map

### ISSUE THREAD

**Issue by mkgrgis** [simon04/locator-tool#52]
Firefox 78.
Steps to reproduce
1. Select category Pavlovsk park https://locator-tool.toolforge.org/#/map?category=Pavlovsk%20park&categoryDepth=3
2. "Show on the map" action
3. See a request to https://petscan.wmflabs.org/?categories=Pavlovsk+park&depth=3&doit=1&format=json&language=commons&ns%5B6%5D=1&project=wikimedia&sparse=1 
4. See CORS error in console

**Comment by simon04** [comment]
Thanks for reporting. I've figured out this problem in October 2020 and opened https://github.com/magnusmanske/petscan_rs/issues/79.

cc: @magnusmanske

**Comment by simon04** [comment]
https://github.com/magnusmanske/petscan_rs/commit/e61ed066c8c71f4b73d1e7c8dc43b55918495cea#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR213

**Comment by mkgrgis** [comment]
Thanks for "cc:" to You and thanks to @magnusmanske !
