### ISSUE TITLE
HTML leaking into interface in time stamp

### ISSUE THREAD

**Issue by hughlilly** [simon04/locator-tool#58]
I'm seeing some HTML coming out as part of the interface in the timestamp, using [File:A large crowd gathered in front of the Albertland Co-op. Dairy Company premises (AM 74626-1).jpg](https://locator-tool.toolforge.org/#/geolocate?files=File:A_large_crowd_gathered_in_front_of_the_Albertland_Co-op._Dairy_Company_premises_(AM_74626-1).jpg) as an example:

```html
<time class="ng-binding">circa 1930 &lt;div style="display: none;"&gt;date QS:P571,+1930-00-00T00:00:00Z/9,P1480,Q5727902&lt;/div&gt;s.</time>
```

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/12046008/134589429-62395eff-1ef4-419c-801c-1c09b419dab8.png">

I'm going to try and run the code locally to see if I can work out what's causing it, but thought I would submit an issue in the meantime.

Thanks
Hugh

Safari 15.0 (16612.1.29.41.4, 16612) on macOS Big Sur 11.6 (20G165)

**Comment by simon04** [comment]
Thanks for reporting. The issue is fixed now.

**Comment by hughlilly** [comment]
Great, thanks!
