### ISSUE TITLE
Categories showing 0 images loaded

### ISSUE THREAD

**Issue by tilmanb** [simon04/locator-tool#59]
The Category `https://commons.wikimedia.org/wiki/Category:Alte_Herrenh%C3%A4user_Stra%C3%9Fe_7_(Hannover)` (and `https://commons.wikimedia.org/wiki/Category:Timber_framing_in_Hannover`, I suspect its the general functionality and not the specific category) cannot be loaded for georeferencing.

Steps to reproduce:
1. Open https://locator-tool.toolforge.org/#/ , do OAuth
2. Enter `https://commons.wikimedia.org/wiki/Category:Alte_Herrenh%C3%A4user_Stra%C3%9Fe_7_(Hannover)` in the Category field
3. click "Kategorie laden zum Georeferenzieren"

Result:

A message saying `0 Dateien für Kategorie https://commons.wikimedia.org/wiki/Category:Alte_Herrenh%C3%A4user_Stra%C3%9Fe_7_(Hannover) geladen!`

The browser console shows

    TypeError: s.query is undefined
    getCategoriesForPrefix ltData.ts:225

Expected result:

There are images in that category that have no location, for example https://commons.wikimedia.org/wiki/File:Alte_Herrenh%C3%A4user_Stra%C3%9Fe_7_7A_Hannover_ehemalige_Meierei_18._Jahrhundert,_Mitteleinfahrt.jpg , so I would expect the images to be loaded by the locator tool.

**Comment by simon04** [comment]
Thanks for reporting. Now also categories specified using the full commons.wikimedia.org URL can be loaded.
