### ISSUE TITLE
SDC support

### ISSUE THREAD

**Issue by HenkvD** [simon04/locator-tool#60]
Currently the locator-tool does not update coordinates on SDC (structured data on Commons)

Changing existing coordinates currently causes mismatches between the {{location}} coordinates and SDC coordinates and puts them in Commons "Category:Pages with local camera coordinates and mismatching SDC coordinates"

Would it be possible to add support for SDC?

**Comment by simon04** [comment]
Relevant properties – https://commons.wikimedia.org/wiki/Commons:Structured_data/Modeling/Location

Type of metadata | Notes | Wikidata property
--- | --- | ---
Coordinates of the photographer | Same as {{Location}} | coordinates of the point of view (P1259) (optional qualifier heading (P7787))
Coordinates of the depicted object | Same as {{Object location}} | coordinates of depicted place (P9149) (optional qualifier heading (P7787))

Relevant API calls

* https://commons.wikimedia.org/w/index.php?title=File:Lesesaal_ULB-Tirol.JPG&action=info 
  * ID=35265782
  * https://www.wikidata.org/wiki/Special:EntityPage/M35265782
* https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=revisions%7Cwbentityusage&meta=&continue=&pageids=35265782&formatversion=2&rvprop=content&rvslots=* (wikibase-mediainfo)
* https://www.wikidata.org/w/api.php?action=help&modules=wbcreateclaim
* https://www.wikidata.org/w/api.php?action=help&modules=wbsetclaimvalue

Example edits: https://commons.wikimedia.org/w/index.php?title=File:Boznerplatz3.JPG&action=history
