### ISSUE TITLE
Use better icon for "Write to Disk"

### ISSUE THREAD

**Issue by jidanni** [simon04/locator-tool#65]
In the green buttons, there is an odd symbol, "--o--".
Maybe use "💾" as it seems to mean "write to disk" better.
Or maybe just put the word "Save" or "Write" on that button.

**Comment by samwilson** [comment]
It looks like it's the `git-commit` Octicon: https://primer.style/design/foundations/icons/git-commit-24

I agree, a more save-like icon might be more communicative of the purpose.

**Comment by simon04** [comment]
Migrated to bootstrap-icon https://icons.getbootstrap.com/icons/save/
