### ISSUE TITLE
Evaluate Wikimedia GitLab (Free and Open) instead of GitHub

### ISSUE THREAD

**Issue by valerio-bozzolan** [simon04/locator-tool#72]
First: thanks for this lovely tool :)

It may be interesting to evaluate Wikimedia GitLab (instead of GitHub):

https://gitlab.wikimedia.org/

Benefits for users:

- no need to become a Microsoft customer to propose issues and pull requests (Microsoft acquired GitHub for 7 billion dollars)
- no need to execute proprietary JavaScript in the browser web to have all features
- https://meta.wikimedia.org/wiki/Wikimedians_for_software_freedom#GitHub

Benefits for maintainers:

- none :D LOL just migration pain, but you will become heroes, forever

**Comment by simon04** [comment]
I've created https://gitlab.wikimedia.org/toolforge-repos/locator-tool as mirror.
